@tool
class_name FGUIBindingCodeGenerator
extends RefCounted

const GENERATED_MARKER := "# Generated by FairyGUI Godot. DO NOT EDIT."
const GENERATOR_VERSION := 9
const DEFAULT_OUTPUT_DIR := "res://generated/fairygui"
const REGISTRY_FILE := "registry.gd"
const MANIFEST_FILE := "manifest.json"

const TYPE_NAMES := {
	FGUIEnums.OBJECT_IMAGE: "FGUIImage",
	FGUIEnums.OBJECT_MOVIE_CLIP: "FGUIMovieClip",
	FGUIEnums.OBJECT_SWF: "FGUIObject",
	FGUIEnums.OBJECT_GRAPH: "FGUIGraph",
	FGUIEnums.OBJECT_LOADER: "FGUILoader",
	FGUIEnums.OBJECT_GROUP: "FGUIGroup",
	FGUIEnums.OBJECT_TEXT: "FGUITextField",
	FGUIEnums.OBJECT_RICH_TEXT: "FGUIRichTextField",
	FGUIEnums.OBJECT_INPUT_TEXT: "FGUITextInput",
	FGUIEnums.OBJECT_COMPONENT: "FGUIComponent",
	FGUIEnums.OBJECT_LIST: "FGUIList",
	FGUIEnums.OBJECT_LABEL: "FGUILabel",
	FGUIEnums.OBJECT_BUTTON: "FGUIButton",
	FGUIEnums.OBJECT_COMBO_BOX: "FGUIComboBox",
	FGUIEnums.OBJECT_PROGRESS_BAR: "FGUIProgressBar",
	FGUIEnums.OBJECT_SLIDER: "FGUISlider",
	FGUIEnums.OBJECT_SCROLL_BAR: "FGUIScrollBar",
	FGUIEnums.OBJECT_TREE: "FGUITree",
	FGUIEnums.OBJECT_LOADER_3D: "FGUILoader3D",
}

const TYPE_SCRIPT_PATHS := {
	"FGUIObject": "res://addons/fairygui/ui/gobject.gd",
	"FGUIImage": "res://addons/fairygui/ui/gimage.gd",
	"FGUIMovieClip": "res://addons/fairygui/ui/gmovie_clip.gd",
	"FGUIGraph": "res://addons/fairygui/ui/ggraph.gd",
	"FGUILoader": "res://addons/fairygui/ui/gloader.gd",
	"FGUIGroup": "res://addons/fairygui/ui/ggroup.gd",
	"FGUITextField": "res://addons/fairygui/ui/gtext_field.gd",
	"FGUIRichTextField": "res://addons/fairygui/ui/grich_text_field.gd",
	"FGUITextInput": "res://addons/fairygui/ui/gtext_input.gd",
	"FGUIComponent": "res://addons/fairygui/ui/gcomponent.gd",
	"FGUIList": "res://addons/fairygui/ui/glist.gd",
	"FGUILabel": "res://addons/fairygui/ui/glabel.gd",
	"FGUIButton": "res://addons/fairygui/ui/gbutton.gd",
	"FGUIComboBox": "res://addons/fairygui/ui/gcombo_box.gd",
	"FGUIProgressBar": "res://addons/fairygui/ui/gprogress_bar.gd",
	"FGUISlider": "res://addons/fairygui/ui/gslider.gd",
	"FGUIScrollBar": "res://addons/fairygui/ui/gscroll_bar.gd",
	"FGUITree": "res://addons/fairygui/ui/gtree.gd",
	"FGUILoader3D": "res://addons/fairygui/ui/gloader3d.gd",
}

const COMPONENT_TYPE_NAMES := {
	"FGUIComponent": true,
	"FGUIList": true,
	"FGUILabel": true,
	"FGUIButton": true,
	"FGUIComboBox": true,
	"FGUIProgressBar": true,
	"FGUISlider": true,
	"FGUIScrollBar": true,
	"FGUITree": true,
}

const RESERVED_WORDS := {
	"and": true,
	"as": true,
	"assert": true,
	"await": true,
	"break": true,
	"breakpoint": true,
	"class": true,
	"class_name": true,
	"const": true,
	"continue": true,
	"elif": true,
	"else": true,
	"enum": true,
	"extends": true,
	"false": true,
	"for": true,
	"func": true,
	"if": true,
	"in": true,
	"is": true,
	"match": true,
	"namespace": true,
	"not": true,
	"null": true,
	"or": true,
	"pass": true,
	"preload": true,
	"return": true,
	"self": true,
	"signal": true,
	"static": true,
	"super": true,
	"trait": true,
	"true": true,
	"var": true,
	"void": true,
	"when": true,
	"while": true,
	"yield": true,
}

var _reserved_names_cache: Dictionary = {}


func generate(
		resource_paths: PackedStringArray,
		output_dir: String = DEFAULT_OUTPUT_DIR,
		class_prefix: String = "UI_",
		include_default_names: bool = false,
		registry_path: String = "",
		include_internal_components: bool = false
	) -> Dictionary:
	var result := {
		"ok": false,
		"generated_files": PackedStringArray(),
		"removed_files": PackedStringArray(),
		"unchanged_files": PackedStringArray(),
		"warnings": PackedStringArray(),
		"errors": PackedStringArray(),
		"bindings": {},
	}
	var normalized_output := _normalize_output_dir(output_dir)
	if not _is_safe_resource_path(normalized_output) or normalized_output == "res://":
		result.errors.append("FairyGUI binding output must be inside res://: %s" % normalized_output)
		return result
	var normalized_registry := registry_path.replace("\\", "/").simplify_path()
	if normalized_registry == "":
		normalized_registry = "%s/%s" % [normalized_output, REGISTRY_FILE]
	if not _is_safe_resource_path(normalized_registry) or not normalized_registry.ends_with(".gd"):
		result.errors.append("FairyGUI binding registry must be a .gd file inside res://: %s" % normalized_registry)
		return result

	var entries: Array[Dictionary] = []
	var seen_paths: Dictionary = {}
	var requested_paths: Dictionary = {}
	var queue: Array = []
	for value: String in resource_paths:
		var requested_path := _normalize_resource_path(value)
		if requested_path == "" or requested_paths.has(requested_path):
			continue
		requested_paths[requested_path] = true
		queue.append(requested_path)
	queue.sort()
	var queue_index := 0
	while queue_index < queue.size():
		var resource_path := _normalize_resource_path(str(queue[queue_index]))
		queue_index += 1
		if resource_path == "" or seen_paths.has(resource_path):
			continue
		seen_paths[resource_path] = true
		if not ResourceLoader.exists(resource_path):
			result.errors.append("FairyGUI package resource does not exist: %s" % resource_path)
			continue
		var loaded: Resource = ResourceLoader.load(resource_path)
		if not loaded is FGUIPackageResource:
			result.errors.append("Resource is not an FGUIPackageResource: %s" % resource_path)
			continue
		var package_resource := loaded as FGUIPackageResource
		var package := package_resource.acquire_package()
		if package == null:
			result.errors.append("Could not acquire FairyGUI package: %s" % resource_path)
			continue
		entries.append({
			"path": resource_path,
			"resource": package_resource,
			"package": package,
			"generate": requested_paths.has(resource_path),
		})
		var base_dir := resource_path.get_base_dir()
		for dependency: Dictionary in package.dependencies:
			var dependency_name := str(dependency.get("name", ""))
			if dependency_name == "":
				continue
			var dependency_path := "%s/%s.fui" % [base_dir, dependency_name]
			if ResourceLoader.exists(dependency_path) and not seen_paths.has(dependency_path):
				queue.append(dependency_path)
			elif not ResourceLoader.exists(dependency_path):
				result.warnings.append("FairyGUI package %s dependency is missing: %s" % [package.name, dependency_path])

	if not result.errors.is_empty():
		_release_entries(entries)
		return result

	entries.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return str(a.path) < str(b.path))
	var schemas := _build_schemas(
		entries,
		normalized_output,
		class_prefix,
		include_default_names,
		include_internal_components,
		result
	)
	if not result.errors.is_empty():
		_release_entries(entries)
		return result

	var contents: Dictionary = {}
	var bindings: Dictionary = {}
	var input_hashes: Dictionary = {}
	for entry: Dictionary in entries:
		var dependency_resource: FGUIPackageResource = entry.resource
		input_hashes[entry.path] = dependency_resource.content_hash
	for schema: Dictionary in schemas:
		for component: Dictionary in schema.components:
			contents[component.script_path] = _render_component(component)
			bindings[component.url] = component.script_path
			bindings[component.name_url] = component.script_path

	if contents.has(normalized_registry):
		result.errors.append("FairyGUI binding registry collides with a generated component script: %s" % normalized_registry)
		_release_entries(entries)
		return result
	contents[normalized_registry] = _render_registry(bindings)
	var generated_paths := PackedStringArray(contents.keys())
	generated_paths.sort()
	var manifest_path := "%s/%s" % [normalized_output, MANIFEST_FILE]
	var manifest := {
		"generator_version": GENERATOR_VERSION,
		"output_dir": normalized_output,
		"registry_path": normalized_registry,
		"options": {
			"class_prefix": class_prefix,
			"include_default_names": include_default_names,
			"include_internal_components": include_internal_components,
		},
		"inputs": input_hashes,
		"files": Array(generated_paths),
		"bindings": bindings,
	}
	contents[manifest_path] = JSON.stringify(manifest, "\t") + "\n"

	var write_result := _commit_contents(contents, manifest_path, generated_paths, normalized_output)
	result.generated_files = write_result.generated_files
	result.unchanged_files = write_result.unchanged_files
	result.removed_files = write_result.removed_files
	for error: String in write_result.errors:
		result.errors.append(error)
	for warning: String in write_result.warnings:
		result.warnings.append(warning)
	result.bindings = bindings
	result.ok = result.errors.is_empty()
	_release_entries(entries)
	return result


func generated_script_path_for(
		package: FGUIPackage,
		component_name: String,
		output_dir: String = DEFAULT_OUTPUT_DIR,
		class_prefix: String = "UI_"
	) -> String:
	if package == null:
		return ""
	var item := package.get_item_by_name(component_name)
	if item == null or item.type != FGUIEnums.PACKAGE_ITEM_COMPONENT:
		return ""
	var normalized_output := _normalize_output_dir(output_dir)
	var manifest_path := "%s/%s" % [normalized_output, MANIFEST_FILE]
	if FileAccess.file_exists(manifest_path):
		var manifest: Variant = JSON.parse_string(FileAccess.get_file_as_string(manifest_path))
		if manifest is Dictionary:
			var url := "ui://%s%s" % [package.id, item.id]
			var manifest_path_value := str(manifest.get("bindings", {}).get(url, ""))
			if manifest_path_value != "":
				return manifest_path_value
	var package_segment := _class_segment(package.name, package.id)
	var component_segment := _class_segment(item.name, item.id)
	var generated_class_name := _sanitize_class_prefix(class_prefix) + package_segment + component_segment
	var package_dir := _member_identifier(package.name, "package_%s" % package.id)
	return "%s/%s/%s.gd" % [
		normalized_output,
		package_dir,
		_member_identifier(generated_class_name, "component_%s" % item.id),
	]


func _build_schemas(
		entries: Array[Dictionary],
		output_dir: String,
		class_prefix: String,
		include_default_names: bool,
		include_internal_components: bool,
		result: Dictionary
	) -> Array[Dictionary]:
	var schemas: Array[Dictionary] = []
	var component_map: Dictionary = {}
	var used_class_names: Dictionary = {}
	var used_package_dirs: Dictionary = {}
	var global_class_paths: Dictionary = {}
	for class_info: Dictionary in ProjectSettings.get_global_class_list():
		global_class_paths[str(class_info.get("class", ""))] = str(class_info.get("path", ""))
	var prefix := _sanitize_class_prefix(class_prefix)

	for entry: Dictionary in entries:
		if not bool(entry.generate):
			continue
		var package: FGUIPackage = entry.package
		var variant_item_ids: Dictionary = {}
		for source_item: FGUIPackageItem in package.items:
			for variant_id: Variant in source_item.branches:
				if variant_id != null and str(variant_id) != "":
					variant_item_ids[str(variant_id)] = true
			for variant_id: Variant in source_item.high_resolution:
				if variant_id != null and str(variant_id) != "":
					variant_item_ids[str(variant_id)] = true
		var package_segment := _class_segment(package.name, package.id)
		var package_dir := _member_identifier(package.name, "package_%s" % package.id)
		if used_package_dirs.has(package_dir):
			var package_dir_base := "%s_%s" % [package_dir, _member_identifier(package.id, "package")]
			package_dir = package_dir_base
			var package_dir_suffix := 2
			while used_package_dirs.has(package_dir):
				package_dir = "%s_%d" % [package_dir_base, package_dir_suffix]
				package_dir_suffix += 1
		used_package_dirs[package_dir] = true
		var schema := {
			"source_path": entry.path,
			"resource": entry.resource,
			"package": package,
			"package_dir": package_dir,
			"components": [],
		}
		for item: FGUIPackageItem in package.items:
			if item.type != FGUIEnums.PACKAGE_ITEM_COMPONENT \
				or (not item.exported and not include_internal_components) \
				or variant_item_ids.has(item.id):
				continue
			var generated_class_name := prefix + package_segment + _class_segment(item.name, item.id)
			if used_class_names.has(generated_class_name):
				var original_name := generated_class_name
				var collision_base := "%s%s" % [generated_class_name, _class_segment(item.id, "Component")]
				generated_class_name = collision_base
				var collision_suffix := 2
				while used_class_names.has(generated_class_name):
					generated_class_name = "%s%d" % [collision_base, collision_suffix]
					collision_suffix += 1
				result.warnings.append("Generated class name collision for %s/%s; using %s instead of %s." % [
					package.name,
					item.name,
					generated_class_name,
					original_name,
				])
			used_class_names[generated_class_name] = true
			var script_path := "%s/%s/%s.gd" % [
				output_dir,
				package_dir,
				_member_identifier(generated_class_name, "component_%s" % item.id),
			]
			var existing_global_path := str(global_class_paths.get(generated_class_name, ""))
			if existing_global_path != "" and existing_global_path != script_path and not existing_global_path.begins_with(output_dir + "/"):
				result.errors.append("Generated class %s for %s/%s conflicts with %s." % [
					generated_class_name,
					package.name,
					item.name,
					existing_global_path,
				])
			var component := {
				"key": _component_key(package.id, item.id),
				"package": package,
				"source_path": entry.path,
				"item": item,
				"class_name": generated_class_name,
				"base_type": _type_name(item.object_type),
				"script_path": script_path,
				"url": "ui://%s%s" % [package.id, item.id],
				"name_url": "ui://%s/%s" % [package.name, item.name],
				"members": [],
			}
			schema.components.append(component)
			component_map[_component_key(package.id, item.id)] = component
			for variant: FGUIPackageItem in _component_variants(item):
				component_map[_component_key(package.id, variant.id)] = component
		schemas.append(schema)

	for schema: Dictionary in schemas:
		for component: Dictionary in schema.components:
			component.members = _scan_component(component.item, component_map, include_default_names, result)
	_resolve_custom_component_types(schemas, result)
	return schemas


func _scan_component(
		item: FGUIPackageItem,
		component_map: Dictionary,
		include_default_names: bool,
		result: Dictionary
	) -> Array[Dictionary]:
	var variants := _component_variants(item)
	if variants.is_empty():
		result.errors.append("Component has no raw data: %s/%s" % [item.owner.name, item.name])
		return []
	var members_by_key: Dictionary = {}
	for variant: FGUIPackageItem in variants:
		var variant_members := _scan_component_variant(item, variant, component_map, include_default_names, result)
		if not result.errors.is_empty():
			return []
		var occurrences: Dictionary = {}
		for member: Dictionary in variant_members:
			var occurrence_key := "%s:%d:%s" % [member.kind, str(member.source_name).length(), member.source_name]
			var occurrence := int(occurrences.get(occurrence_key, 0))
			occurrences[occurrence_key] = occurrence + 1
			var merge_key := "%s:%d" % [occurrence_key, occurrence]
			if not members_by_key.has(merge_key):
				var copy := member.duplicate(true)
				copy.variant_count = 1
				members_by_key[merge_key] = copy
			else:
				var existing: Dictionary = members_by_key[merge_key]
				existing.variant_count = int(existing.variant_count) + 1
				_merge_variant_member(existing, member, item, result)

	var raw_members: Array[Dictionary] = []
	for member: Dictionary in members_by_key.values():
		member.required = int(member.variant_count) == variants.size()
		if not bool(member.required):
			result.warnings.append("Branch-dependent member %s/%s.%s is optional in generated bindings." % [
				item.owner.name,
				item.name,
				member.source_name,
			])
		raw_members.append(member)

	raw_members.sort_custom(func(a: Dictionary, b: Dictionary) -> bool:
		var kind_order := {"child": 0, "controller": 1, "transition": 2}
		var a_kind := int(kind_order.get(str(a.kind), 99))
		var b_kind := int(kind_order.get(str(b.kind), 99))
		if a_kind != b_kind:
			return a_kind < b_kind
		var a_name := str(a.source_name)
		var b_name := str(b.source_name)
		if a_name != b_name:
			return a_name < b_name
		var a_type := str(a.type_name)
		var b_type := str(b.type_name)
		if a_type != b_type:
			return a_type < b_type
		return int(a.order) < int(b.order)
	)
	var reserved_names := _reserved_member_names(_type_name(item.object_type))
	var used_names: Dictionary = {}
	for member: Dictionary in raw_members:
		var fallback := "%s_%s" % [member.kind, _stable_identifier_suffix(str(member.source_name))]
		var variable_name := _member_identifier(member.source_name, fallback)
		if reserved_names.has(variable_name):
			var original_name := variable_name
			variable_name = "ui_%s" % variable_name
			result.warnings.append("Member '%s' in %s/%s conflicts with inherited member '%s'; generated '%s'." % [
				member.source_name,
				item.owner.name,
				item.name,
				original_name,
				variable_name,
			])
		var base_name := variable_name
		var suffix := 2
		while used_names.has(variable_name):
			variable_name = "%s_%d" % [base_name, suffix]
			suffix += 1
		if variable_name != base_name:
			result.warnings.append("Member name collision in %s/%s for '%s'; generated '%s'." % [
				item.owner.name,
				item.name,
				member.source_name,
				variable_name,
			])
		used_names[variable_name] = true
		member.var_name = variable_name
	return raw_members


func _scan_component_variant(
		item: FGUIPackageItem,
		content_item: FGUIPackageItem,
		component_map: Dictionary,
		include_default_names: bool,
		result: Dictionary
	) -> Array[Dictionary]:
	var raw_members: Array[Dictionary] = []
	if content_item == null or content_item.raw_data == null:
		result.errors.append("Component variant has no raw data: %s/%s (%s)" % [
			item.owner.name,
			item.name,
			content_item.id if content_item != null else "<null>",
		])
		return raw_members
	var buffer := _clone_buffer(content_item.raw_data)

	if buffer.seek(0, 2):
		var child_count := buffer.read_i16()
		for index in child_count:
			var data_len := buffer.read_i16()
			var begin_pos := buffer.pos
			var end_pos := begin_pos + data_len
			if data_len <= 0 or end_pos > buffer.get_length():
				result.errors.append("Invalid child block in %s/%s variant %s at index %d." % [
					item.owner.name,
					item.name,
					content_item.id,
					index,
				])
				return raw_members
			if buffer.seek(begin_pos, 0):
				var object_type := buffer.read_i8()
				var source_id: Variant = buffer.read_s()
				var source_package_id: Variant = buffer.read_s()
				buffer.read_s() # child id
				var source_name := _string_or_empty(buffer.read_s())
				if source_name != "" and (include_default_names or not _is_default_child_name(source_name)):
					var source_item := _resolve_source_item(content_item, source_id, source_package_id)
					var type_name := _type_name(object_type)
					var fallback_type := type_name
					var custom_component_key := ""
					var custom_script_path := ""
					if source_item != null:
						fallback_type = _type_name(source_item.object_type)
						type_name = fallback_type
						var key := _component_key(source_item.owner.id, source_item.id)
						if component_map.has(key):
							var target_component: Dictionary = component_map[key]
							type_name = str(target_component["class_name"])
							custom_component_key = str(target_component["key"])
							custom_script_path = str(target_component["script_path"])
					elif source_id != null:
						result.warnings.append("Could not resolve child source %s in %s/%s.%s; using %s." % [
							str(source_id),
							item.owner.name,
							item.name,
							source_name,
							type_name,
						])
					raw_members.append({
						"kind": "child",
						"source_name": source_name,
						"type_name": type_name,
						"fallback_type": fallback_type,
						"custom_component_key": custom_component_key,
						"custom_script_path": custom_script_path,
						"order": index,
					})
			buffer.pos = end_pos

	buffer.pos = 0
	if buffer.seek(0, 1):
		var controller_count := buffer.read_i16()
		for index in controller_count:
			var next_pos := buffer.read_i16() + buffer.pos
			var begin_pos := buffer.pos
			if buffer.seek(begin_pos, 0):
				var source_name := _string_or_empty(buffer.read_s())
				if source_name != "":
					raw_members.append({
						"kind": "controller",
						"source_name": source_name,
						"type_name": "FGUIController",
						"order": index,
					})
			buffer.pos = next_pos

	buffer.pos = 0
	if buffer.seek(0, 5):
		var transition_count := buffer.read_i16()
		for index in transition_count:
			var next_pos := buffer.read_i16() + buffer.pos
			var source_name := _string_or_empty(buffer.read_s())
			if source_name != "":
				raw_members.append({
					"kind": "transition",
					"source_name": source_name,
					"type_name": "FGUITransition",
					"order": index,
				})
			buffer.pos = next_pos
	return raw_members


func _component_variants(item: FGUIPackageItem) -> Array[FGUIPackageItem]:
	var result: Array[FGUIPackageItem] = []
	if item == null or item.owner == null:
		return result
	var queue: Array[FGUIPackageItem] = [item]
	var seen: Dictionary = {}
	var index := 0
	while index < queue.size():
		var candidate := queue[index]
		index += 1
		if candidate == null or seen.has(candidate.id):
			continue
		seen[candidate.id] = true
		if candidate.type == FGUIEnums.PACKAGE_ITEM_COMPONENT and candidate.raw_data != null:
			result.append(candidate)
		for variant_id: Variant in candidate.branches:
			var branch_item: FGUIPackageItem = candidate.owner.get_item_by_id(str(variant_id)) if variant_id != null else null
			if branch_item != null and not seen.has(branch_item.id):
				queue.append(branch_item)
		for variant_id: Variant in candidate.high_resolution:
			var high_resolution_item: FGUIPackageItem = candidate.owner.get_item_by_id(str(variant_id)) if variant_id != null else null
			if high_resolution_item != null and not seen.has(high_resolution_item.id):
				queue.append(high_resolution_item)
	return result


func _merge_variant_member(
		existing: Dictionary,
		incoming: Dictionary,
		item: FGUIPackageItem,
		result: Dictionary
	) -> void:
	existing.order = mini(int(existing.order), int(incoming.order))
	if str(existing.kind) != "child":
		return
	var same_type := str(existing.type_name) == str(incoming.type_name)
	var same_component := str(existing.get("custom_component_key", "")) == str(incoming.get("custom_component_key", ""))
	if same_type and same_component:
		return
	var common_type := _common_child_type(
		str(existing.get("fallback_type", existing.type_name)),
		str(incoming.get("fallback_type", incoming.type_name))
	)
	if not bool(existing.get("type_conflict_reported", false)):
		result.warnings.append("Variant member type conflict in %s/%s.%s; using %s instead of %s and %s." % [
			item.owner.name,
			item.name,
			existing.source_name,
			common_type,
			existing.type_name,
			incoming.type_name,
		])
		existing.type_conflict_reported = true
	existing.type_name = common_type
	existing.fallback_type = common_type
	existing.custom_component_key = ""
	existing.custom_script_path = ""


static func _common_child_type(left: String, right: String) -> String:
	if left == right:
		return left
	if COMPONENT_TYPE_NAMES.has(left) and COMPONENT_TYPE_NAMES.has(right):
		return "FGUIComponent"
	return "FGUIObject"


func _resolve_custom_component_types(schemas: Array[Dictionary], result: Dictionary) -> void:
	var graph: Dictionary = {}
	for schema: Dictionary in schemas:
		for component: Dictionary in schema.components:
			graph[str(component.key)] = []

	for schema: Dictionary in schemas:
		for component: Dictionary in schema.components:
			var dependencies: Array = graph[str(component.key)]
			for member: Dictionary in component.members:
				var dependency_key := str(member.get("custom_component_key", ""))
				if dependency_key != "" and not dependencies.has(dependency_key):
					dependencies.append(dependency_key)

	for schema: Dictionary in schemas:
		for component: Dictionary in schema.components:
			var aliases: Array[Dictionary] = []
			var aliases_by_path: Dictionary = {}
			var component_key := str(component.key)
			for member: Dictionary in component.members:
				var dependency_key := str(member.get("custom_component_key", ""))
				if dependency_key == "":
					continue
				var fallback_type := str(member.get("fallback_type", "FGUIComponent"))
				if _graph_has_path(graph, dependency_key, component_key, {}):
					var generated_type := str(member.type_name)
					member.type_name = fallback_type
					result.warnings.append("Cyclic generated component reference %s/%s.%s uses %s instead of %s." % [
						component.package.name,
						component.item.name,
						member.source_name,
						fallback_type,
						generated_type,
					])
					continue
				var script_path := str(member.get("custom_script_path", ""))
				if script_path == "":
					member.type_name = fallback_type
					result.warnings.append("Generated component reference %s/%s.%s has no script path; using %s." % [
						component.package.name,
						component.item.name,
						member.source_name,
						fallback_type,
					])
					continue
				var alias_name := str(aliases_by_path.get(script_path, ""))
				if alias_name == "":
					alias_name = "_TYPE_%d" % aliases.size()
					aliases_by_path[script_path] = alias_name
					aliases.append({"name": alias_name, "path": script_path})
				member.type_name = alias_name
			component.type_aliases = aliases


func _graph_has_path(graph: Dictionary, start: String, target: String, visiting: Dictionary) -> bool:
	if start == target:
		return true
	if visiting.has(start):
		return false
	visiting[start] = true
	for dependency: Variant in graph.get(start, []):
		if _graph_has_path(graph, str(dependency), target, visiting):
			return true
	visiting.erase(start)
	return false


func _reserved_member_names(type_name: String) -> Dictionary:
	if _reserved_names_cache.has(type_name):
		return (_reserved_names_cache[type_name] as Dictionary).duplicate()
	var result := {
		"create_instance": true,
		"url": true,
		"package_path": true,
		"package_id": true,
		"package_name": true,
		"component_id": true,
		"component_name": true,
		"_on_construct": true,
	}
	var script_path := str(TYPE_SCRIPT_PATHS.get(type_name, TYPE_SCRIPT_PATHS.FGUIObject))
	var script := ResourceLoader.load(script_path) as Script
	if script != null:
		for property: Dictionary in script.get_script_property_list():
			result[str(property.get("name", ""))] = true
		for method: Dictionary in script.get_script_method_list():
			result[str(method.get("name", ""))] = true
		for signal_info: Dictionary in script.get_script_signal_list():
			result[str(signal_info.get("name", ""))] = true
	_reserved_names_cache[type_name] = result.duplicate()
	return result


func _render_component(component: Dictionary) -> String:
	var lines := PackedStringArray()
	lines.append(GENERATED_MARKER)
	lines.append("class_name %s" % component["class_name"])
	lines.append("extends %s" % component.base_type)
	lines.append("")
	lines.append("const URL := %s" % _quote(component.url))
	lines.append("const PACKAGE_PATH := %s" % _quote(component.source_path))
	lines.append("const PACKAGE_ID := %s" % _quote(component.package.id))
	lines.append("const PACKAGE_NAME := %s" % _quote(component.package.name))
	lines.append("const COMPONENT_ID := %s" % _quote(component.item.id))
	lines.append("const COMPONENT_NAME := %s" % _quote(component.item.name))
	for alias: Dictionary in component.get("type_aliases", []):
		lines.append("const %s := preload(%s)" % [alias.name, _quote(alias.path)])
	if not component.members.is_empty():
		lines.append("")
		for member: Dictionary in component.members:
			lines.append("var %s: %s" % [member.var_name, member.type_name])
	lines.append("")
	lines.append("")
	lines.append("static func create_instance(package: FGUIPackage = null) -> %s:" % component["class_name"])
	lines.append("\tif package == null:")
	lines.append("\t\tpackage = FGUIPackage.get_by_id(PACKAGE_ID)")
	lines.append("\tif package == null:")
	lines.append("\t\tpackage = FGUIPackage.get_by_name(PACKAGE_NAME)")
	lines.append("\tif package == null:")
	lines.append("\t\tpackage = FGUIPackage.add_package(PACKAGE_PATH)")
	lines.append("\tif package == null:")
	lines.append("\t\treturn null")
	lines.append("\treturn package.create_object(COMPONENT_NAME) as %s" % component["class_name"])
	lines.append("")
	lines.append("")
	lines.append("func _on_construct() -> void:")
	lines.append("\tsuper._on_construct()")
	if component.members.is_empty():
		lines.append("\tpass")
	else:
		for member: Dictionary in component.members:
			var required := bool(member.get("required", true))
			match str(member.kind):
				"child":
					var child_lookup := "require_child(%s, %s)" % [
						_quote(member.source_name),
						member.type_name,
					] if required else "optional_child(%s, %s)" % [
						_quote(member.source_name),
						member.type_name,
					]
					lines.append("\t%s = %s as %s" % [
						member.var_name,
						child_lookup,
						member.type_name,
					])
				"controller":
					lines.append("\t%s = %s(%s)" % [
						member.var_name,
						"require_controller" if required else "get_controller",
						_quote(member.source_name),
					])
				"transition":
					lines.append("\t%s = %s(%s)" % [
						member.var_name,
						"require_transition" if required else "get_transition",
						_quote(member.source_name),
					])
	return "\n".join(lines) + "\n"


func _render_registry(bindings: Dictionary) -> String:
	var urls := PackedStringArray(bindings.keys())
	urls.sort()
	var lines := PackedStringArray([GENERATED_MARKER, "extends RefCounted", ""])
	lines.append("func get_bindings() -> Dictionary:")
	if urls.is_empty():
		lines.append("\treturn {}")
	else:
		lines.append("\treturn {")
		for url: String in urls:
			lines.append("\t\t%s: %s," % [_quote(url), _quote(str(bindings[url]))])
		lines.append("\t}")
	return "\n".join(lines) + "\n"


func _commit_contents(
		contents: Dictionary,
		manifest_path: String,
		generated_paths: PackedStringArray,
		output_dir: String
	) -> Dictionary:
	var result := {
		"generated_files": PackedStringArray(),
		"unchanged_files": PackedStringArray(),
		"removed_files": PackedStringArray(),
		"warnings": PackedStringArray(),
		"errors": PackedStringArray(),
	}
	var recovery_error := _recover_interrupted_path(manifest_path)
	if recovery_error != OK:
		result.errors.append("Could not recover interrupted generated manifest %s: %s" % [
			manifest_path,
			error_string(recovery_error),
		])
		return result
	var old_manifest := _read_manifest(manifest_path)
	var old_registry_path := str(old_manifest.get("registry_path", "")) if old_manifest is Dictionary else ""
	var recovery_paths := PackedStringArray(contents.keys())
	for value: Variant in old_manifest.get("files", []) if old_manifest is Dictionary else []:
		var old_path := str(value)
		if _is_managed_old_path(old_path, output_dir, old_registry_path) and not recovery_paths.has(old_path):
			recovery_paths.append(old_path)
	for path: String in recovery_paths:
		recovery_error = _recover_interrupted_path(path)
		if recovery_error != OK:
			result.errors.append("Could not recover interrupted generated file %s: %s" % [
				path,
				error_string(recovery_error),
			])
			return result
		if path.get_extension().to_lower() == "gd":
			recovery_error = _recover_interrupted_path(path + ".uid")
			if recovery_error != OK:
				result.errors.append("Could not recover interrupted generated UID %s: %s" % [
					path + ".uid",
					error_string(recovery_error),
				])
				return result
	old_manifest = _read_manifest(manifest_path)
	old_registry_path = str(old_manifest.get("registry_path", "")) if old_manifest is Dictionary else ""
	var changed_paths := PackedStringArray()
	for path: String in contents:
		var content := str(contents[path])
		if FileAccess.file_exists(path) and FileAccess.get_file_as_string(path) == content:
			result.unchanged_files.append(path)
		else:
			changed_paths.append(path)
	changed_paths.sort()
	if changed_paths.has(manifest_path):
		changed_paths.remove_at(changed_paths.find(manifest_path))
		changed_paths.append(manifest_path)

	var new_files: Dictionary = {}
	for path: String in generated_paths:
		new_files[path] = true
	var stale_paths := PackedStringArray()
	var old_files: Array = old_manifest.get("files", []) if old_manifest is Dictionary else []
	for value: Variant in old_files:
		var old_path := str(value)
		if new_files.has(old_path) or not _is_managed_old_path(old_path, output_dir, old_registry_path):
			continue
		if not FileAccess.file_exists(old_path):
			continue
		var first_line := FileAccess.get_file_as_string(old_path).get_slice("\n", 0).strip_edges()
		if first_line == GENERATED_MARKER:
			stale_paths.append(old_path)
	stale_paths.sort()
	var stale_auxiliary_paths := PackedStringArray()
	for path: String in stale_paths:
		if path.get_extension().to_lower() == "gd" and FileAccess.file_exists(path + ".uid"):
			stale_auxiliary_paths.append(path + ".uid")

	var temporary_paths: Dictionary = {}
	for path: String in changed_paths:
		var error := _ensure_parent_directory(path)
		if error != OK:
			result.errors.append("Could not create generated binding directory for %s: %s" % [path, error_string(error)])
			break
		var temporary_path := "%s.fairygui_tmp" % path
		_remove_file(temporary_path)
		var file := FileAccess.open(temporary_path, FileAccess.WRITE)
		if file == null:
			result.errors.append("Could not write temporary generated binding file: %s" % temporary_path)
			break
		file.store_string(str(contents[path]))
		file.close()
		temporary_paths[path] = temporary_path

	if not result.errors.is_empty():
		for temporary_path: String in temporary_paths.values():
			_remove_file(temporary_path)
		return result

	var transaction_paths := changed_paths.duplicate()
	for path: String in stale_paths:
		if not transaction_paths.has(path):
			transaction_paths.append(path)
	for path: String in stale_auxiliary_paths:
		if not transaction_paths.has(path):
			transaction_paths.append(path)
	var backup_paths: Dictionary = {}
	var installed_paths := PackedStringArray()
	for path: String in transaction_paths:
		if not FileAccess.file_exists(path):
			continue
		var backup_path := "%s.fairygui_backup" % path
		_remove_file(backup_path)
		var backup_error := DirAccess.rename_absolute(
			ProjectSettings.globalize_path(path),
			ProjectSettings.globalize_path(backup_path)
		)
		if backup_error != OK:
			result.errors.append("Could not back up generated binding file %s: %s" % [path, error_string(backup_error)])
			break
		backup_paths[path] = backup_path

	if not result.errors.is_empty():
		for rollback_error: String in _rollback_commit(installed_paths, backup_paths, temporary_paths):
			result.errors.append(rollback_error)
		return result

	for path: String in changed_paths:
		var install_error := DirAccess.rename_absolute(
			ProjectSettings.globalize_path(str(temporary_paths[path])),
			ProjectSettings.globalize_path(path)
		)
		if install_error != OK:
			result.errors.append("Could not install generated binding file %s: %s" % [path, error_string(install_error)])
			break
		installed_paths.append(path)

	if not result.errors.is_empty():
		for rollback_error: String in _rollback_commit(installed_paths, backup_paths, temporary_paths):
			result.errors.append(rollback_error)
		return result

	for validation_error: String in _validate_generated_scripts(generated_paths):
		result.errors.append(validation_error)
	if not result.errors.is_empty():
		for rollback_error: String in _rollback_commit(installed_paths, backup_paths, temporary_paths):
			result.errors.append(rollback_error)
		for reload_error: String in _reload_restored_scripts(generated_paths):
			result.errors.append(reload_error)
		return result

	result.generated_files = changed_paths
	result.removed_files = stale_paths
	result.removed_files.append_array(stale_auxiliary_paths)
	for path: String in backup_paths:
		var remove_error := _remove_file(str(backup_paths[path]))
		if remove_error != OK:
			result.warnings.append("Could not remove generated binding backup for %s: %s" % [
				path,
				error_string(remove_error),
			])
	return result


func _read_manifest(path: String) -> Variant:
	if not FileAccess.file_exists(path):
		return {}
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(path))
	return parsed if parsed is Dictionary else {}


func _recover_interrupted_path(path: String) -> Error:
	var temporary_path := "%s.fairygui_tmp" % path
	var backup_path := "%s.fairygui_backup" % path
	var remove_error := _remove_file(temporary_path)
	if remove_error != OK:
		return remove_error
	if not FileAccess.file_exists(backup_path):
		return OK
	if FileAccess.file_exists(path):
		remove_error = _remove_file(path)
		if remove_error != OK:
			return remove_error
	return DirAccess.rename_absolute(
		ProjectSettings.globalize_path(backup_path),
		ProjectSettings.globalize_path(path)
	)


func _rollback_commit(
		installed_paths: PackedStringArray,
		backup_paths: Dictionary,
		temporary_paths: Dictionary
	) -> PackedStringArray:
	var errors := PackedStringArray()
	for path: String in installed_paths:
		var remove_error := _remove_file(path)
		if remove_error != OK:
			errors.append("Could not remove partially installed generated file %s: %s" % [path, error_string(remove_error)])
	for path: String in backup_paths:
		var restore_error := DirAccess.rename_absolute(
			ProjectSettings.globalize_path(str(backup_paths[path])),
			ProjectSettings.globalize_path(path)
		)
		if restore_error != OK:
			errors.append("Could not restore generated binding file %s: %s" % [path, error_string(restore_error)])
	for temporary_path: String in temporary_paths.values():
		var remove_error := _remove_file(temporary_path)
		if remove_error != OK:
			errors.append("Could not remove generated temporary file %s: %s" % [temporary_path, error_string(remove_error)])
	return errors


func _validate_generated_scripts(paths: PackedStringArray) -> PackedStringArray:
	var errors := PackedStringArray()
	for path: String in paths:
		if path.get_extension().to_lower() != "gd":
			continue
		var script := ResourceLoader.load(path, "GDScript", ResourceLoader.CACHE_MODE_REPLACE) as Script
		if script == null or not script.can_instantiate():
			errors.append("Generated binding script failed validation: %s" % path)
	return errors


func _reload_restored_scripts(paths: PackedStringArray) -> PackedStringArray:
	var errors := PackedStringArray()
	for path: String in paths:
		if path.get_extension().to_lower() != "gd" or not FileAccess.file_exists(path):
			continue
		var script := ResourceLoader.load(path, "GDScript", ResourceLoader.CACHE_MODE_REPLACE) as Script
		if script == null or not script.can_instantiate():
			errors.append("Could not reload restored generated binding script: %s" % path)
	return errors


func _ensure_parent_directory(path: String) -> Error:
	return DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(path.get_base_dir()))


func _remove_file(path: String) -> Error:
	if not FileAccess.file_exists(path):
		return OK
	return DirAccess.remove_absolute(ProjectSettings.globalize_path(path))


func _release_entries(entries: Array[Dictionary]) -> void:
	for index in range(entries.size() - 1, -1, -1):
		var entry: Dictionary = entries[index]
		FGUIPackageResource.release_package(entry.package)


func _clone_buffer(source: FGUIByteBuffer) -> FGUIByteBuffer:
	var clone := FGUIByteBuffer.new(source.data)
	clone.string_table = source.string_table
	clone.version = source.version
	return clone


func _resolve_source_item(content_item: FGUIPackageItem, source_id: Variant, source_package_id: Variant) -> FGUIPackageItem:
	if source_id == null:
		return null
	var package: FGUIPackage = content_item.owner
	if source_package_id != null:
		package = FGUIPackage.get_by_id(str(source_package_id))
	return package.get_item_by_id(str(source_id)) if package != null else null


static func _component_key(package_id: String, component_id: String) -> String:
	return "%s:%s" % [package_id, component_id]


static func _type_name(object_type: int) -> String:
	return str(TYPE_NAMES.get(object_type, "FGUIObject"))


static func _normalize_output_dir(path: String) -> String:
	var normalized := path.replace("\\", "/").simplify_path().trim_suffix("/")
	return normalized if normalized != "" else DEFAULT_OUTPUT_DIR


static func _normalize_resource_path(path: String) -> String:
	var normalized := path.replace("\\", "/").simplify_path()
	if normalized.ends_with(".fui"):
		return normalized
	if ResourceLoader.exists(normalized + ".fui"):
		return normalized + ".fui"
	return normalized


static func _is_safe_resource_path(path: String) -> bool:
	if not path.begins_with("res://"):
		return false
	for segment: String in path.trim_prefix("res://").split("/", false):
		if segment == "..":
			return false
	return true


static func _is_managed_old_path(path: String, output_dir: String, registry_path: String) -> bool:
	var normalized := path.replace("\\", "/").simplify_path()
	if not _is_safe_resource_path(normalized):
		return false
	if normalized.begins_with(output_dir + "/"):
		return true
	return registry_path != "" and normalized == registry_path.replace("\\", "/").simplify_path()


static func _sanitize_class_prefix(value: String) -> String:
	var cleaned := _ascii_identifier_source(value)
	if cleaned == "":
		return "UI_"
	if value.ends_with("_") and not cleaned.ends_with("_"):
		cleaned += "_"
	if cleaned[0].is_valid_int():
		cleaned = "UI_" + cleaned
	return cleaned


static func _class_segment(value: String, fallback: String) -> String:
	var cleaned := _ascii_identifier_source(value)
	var result := cleaned.to_pascal_case()
	if result == "":
		result = _ascii_identifier_source(fallback).to_pascal_case()
	if result == "":
		result = "Component"
	if result[0].is_valid_int():
		result = "N" + result
	return result


static func _member_identifier(value: String, fallback: String) -> String:
	var cleaned := _ascii_identifier_source(value)
	var result := cleaned.to_snake_case().to_lower()
	if result == "":
		result = _ascii_identifier_source(fallback).to_snake_case().to_lower()
	if result == "":
		result = "member"
	if result[0].is_valid_int():
		result = "ui_" + result
	if RESERVED_WORDS.has(result):
		result = "ui_" + result
	return result


static func _ascii_identifier_source(value: String) -> String:
	var result := ""
	var previous_was_separator := false
	for index in value.length():
		var code := value.unicode_at(index)
		var valid := (code >= 48 and code <= 57) or (code >= 65 and code <= 90) or (code >= 97 and code <= 122) or code == 95
		if valid:
			result += value.substr(index, 1)
			previous_was_separator = false
		elif not previous_was_separator:
			result += "_"
			previous_was_separator = true
	return result.strip_edges().trim_prefix("_").trim_suffix("_")


static func _stable_identifier_suffix(value: String) -> String:
	return value.sha256_text().substr(0, 10)


static func _is_default_child_name(value: String) -> bool:
	if value.length() < 2 or value[0].to_lower() != "n":
		return false
	return value.substr(1).is_valid_int()


static func _string_or_empty(value: Variant) -> String:
	return "" if value == null else str(value)


static func _quote(value: String) -> String:
	return JSON.stringify(value)
