class_name FairyGUI
extends RefCounted

const ByteBuffer := preload("res://addons/fairygui/core/byte_buffer.gd")
const Enums := preload("res://addons/fairygui/core/enums.gd")
const Package := preload("res://addons/fairygui/core/ui_package.gd")
const PackageItem := preload("res://addons/fairygui/core/package_item.gd")
const ObjectFactory := preload("res://addons/fairygui/ui/ui_object_factory.gd")
const Root := preload("res://addons/fairygui/ui/groot.gd")
const Object := preload("res://addons/fairygui/ui/gobject.gd")
const Component := preload("res://addons/fairygui/ui/gcomponent.gd")
const ImageObject := preload("res://addons/fairygui/ui/gimage.gd")
const TextField := preload("res://addons/fairygui/ui/gtext_field.gd")
const RichTextField := preload("res://addons/fairygui/ui/grich_text_field.gd")
const TextInput := preload("res://addons/fairygui/ui/gtext_input.gd")
const Loader := preload("res://addons/fairygui/ui/gloader.gd")
const Graph := preload("res://addons/fairygui/ui/ggraph.gd")
const Group := preload("res://addons/fairygui/ui/ggroup.gd")
const Label := preload("res://addons/fairygui/ui/glabel.gd")
const Button := preload("res://addons/fairygui/ui/gbutton.gd")
const ProgressBar := preload("res://addons/fairygui/ui/gprogress_bar.gd")
const Slider := preload("res://addons/fairygui/ui/gslider.gd")
const ScrollBar := preload("res://addons/fairygui/ui/gscroll_bar.gd")
const ComboBox := preload("res://addons/fairygui/ui/gcombo_box.gd")
const List := preload("res://addons/fairygui/ui/glist.gd")
const Tree := preload("res://addons/fairygui/ui/gtree.gd")
const WindowObject := preload("res://addons/fairygui/ui/window.gd")
const PopupMenu := preload("res://addons/fairygui/ui/popup_menu.gd")
const DragDropManager := preload("res://addons/fairygui/ui/drag_drop_manager.gd")
const AsyncOperation := preload("res://addons/fairygui/ui/async_operation.gd")
const Transition := preload("res://addons/fairygui/ui/transition.gd")
