class_name FGUIEnums
extends RefCounted

const BUTTON_COMMON := 0
const BUTTON_CHECK := 1
const BUTTON_RADIO := 2

const AUTOSIZE_NONE := 0
const AUTOSIZE_BOTH := 1
const AUTOSIZE_HEIGHT := 2
const AUTOSIZE_SHRINK := 3
const AUTOSIZE_ELLIPSIS := 4

const ALIGN_LEFT := 0
const ALIGN_CENTER := 1
const ALIGN_RIGHT := 2

const VERT_ALIGN_TOP := 0
const VERT_ALIGN_MIDDLE := 1
const VERT_ALIGN_BOTTOM := 2

const LOADER_FILL_NONE := 0
const LOADER_FILL_SCALE := 1
const LOADER_FILL_SCALE_MATCH_HEIGHT := 2
const LOADER_FILL_SCALE_MATCH_WIDTH := 3
const LOADER_FILL_SCALE_FREE := 4
const LOADER_FILL_SCALE_NO_BORDER := 5

const LIST_LAYOUT_SINGLE_COLUMN := 0
const LIST_LAYOUT_SINGLE_ROW := 1
const LIST_LAYOUT_FLOW_HORIZONTAL := 2
const LIST_LAYOUT_FLOW_VERTICAL := 3
const LIST_LAYOUT_PAGINATION := 4

const LIST_SELECTION_SINGLE := 0
const LIST_SELECTION_MULTIPLE := 1
const LIST_SELECTION_MULTIPLE_SINGLE_CLICK := 2
const LIST_SELECTION_NONE := 3

const PACKAGE_ITEM_IMAGE := 0
const PACKAGE_ITEM_MOVIE_CLIP := 1
const PACKAGE_ITEM_SOUND := 2
const PACKAGE_ITEM_COMPONENT := 3
const PACKAGE_ITEM_ATLAS := 4
const PACKAGE_ITEM_FONT := 5
const PACKAGE_ITEM_SWF := 6
const PACKAGE_ITEM_MISC := 7
const PACKAGE_ITEM_UNKNOWN := 8
const PACKAGE_ITEM_SPINE := 9
const PACKAGE_ITEM_DRAGON_BONES := 10

const OBJECT_IMAGE := 0
const OBJECT_MOVIE_CLIP := 1
const OBJECT_SWF := 2
const OBJECT_GRAPH := 3
const OBJECT_LOADER := 4
const OBJECT_GROUP := 5
const OBJECT_TEXT := 6
const OBJECT_RICH_TEXT := 7
const OBJECT_INPUT_TEXT := 8
const OBJECT_COMPONENT := 9
const OBJECT_LIST := 10
const OBJECT_LABEL := 11
const OBJECT_BUTTON := 12
const OBJECT_COMBO_BOX := 13
const OBJECT_PROGRESS_BAR := 14
const OBJECT_SLIDER := 15
const OBJECT_SCROLL_BAR := 16
const OBJECT_TREE := 17
const OBJECT_LOADER_3D := 18

const OVERFLOW_VISIBLE := 0
const OVERFLOW_HIDDEN := 1
const OVERFLOW_SCROLL := 2

const PROGRESS_TITLE_PERCENT := 0
const PROGRESS_TITLE_VALUE_AND_MAX := 1
const PROGRESS_TITLE_VALUE := 2
const PROGRESS_TITLE_MAX := 3

const SCROLLBAR_DEFAULT := 0
const SCROLLBAR_VISIBLE := 1
const SCROLLBAR_AUTO := 2
const SCROLLBAR_HIDDEN := 3

const SCROLL_HORIZONTAL := 0
const SCROLL_VERTICAL := 1
const SCROLL_BOTH := 2

const FLIP_NONE := 0
const FLIP_HORIZONTAL := 1
const FLIP_VERTICAL := 2
const FLIP_BOTH := 3

const BLEND_NORMAL := 0
const BLEND_NONE := 1
const BLEND_ADD := 2
const BLEND_MULTIPLY := 3
const BLEND_SCREEN := 4
const BLEND_ERASE := 5
const BLEND_MASK := 6
const BLEND_BELOW := 7
const BLEND_OFF := 8
const BLEND_ONE_ONE_MINUS_SRC_ALPHA := 9
const BLEND_CUSTOM_1 := 10
const BLEND_CUSTOM_2 := 11
const BLEND_CUSTOM_3 := 12

const CHILDREN_RENDER_ASCENT := 0
const CHILDREN_RENDER_DESCENT := 1
const CHILDREN_RENDER_ARCH := 2

const GROUP_LAYOUT_NONE := 0
const GROUP_LAYOUT_HORIZONTAL := 1
const GROUP_LAYOUT_VERTICAL := 2

const POPUP_AUTO := 0
const POPUP_UP := 1
const POPUP_DOWN := 2

const RELATION_LEFT_LEFT := 0
const RELATION_LEFT_CENTER := 1
const RELATION_LEFT_RIGHT := 2
const RELATION_CENTER_CENTER := 3
const RELATION_RIGHT_LEFT := 4
const RELATION_RIGHT_CENTER := 5
const RELATION_RIGHT_RIGHT := 6
const RELATION_TOP_TOP := 7
const RELATION_TOP_MIDDLE := 8
const RELATION_TOP_BOTTOM := 9
const RELATION_MIDDLE_MIDDLE := 10
const RELATION_BOTTOM_TOP := 11
const RELATION_BOTTOM_MIDDLE := 12
const RELATION_BOTTOM_BOTTOM := 13
const RELATION_WIDTH := 14
const RELATION_HEIGHT := 15
const RELATION_LEFT_EXT_LEFT := 16
const RELATION_LEFT_EXT_RIGHT := 17
const RELATION_RIGHT_EXT_LEFT := 18
const RELATION_RIGHT_EXT_RIGHT := 19
const RELATION_TOP_EXT_TOP := 20
const RELATION_TOP_EXT_BOTTOM := 21
const RELATION_BOTTOM_EXT_TOP := 22
const RELATION_BOTTOM_EXT_BOTTOM := 23
const RELATION_SIZE := 24

const FILL_NONE := 0
const FILL_HORIZONTAL := 1
const FILL_VERTICAL := 2
const FILL_RADIAL_90 := 3
const FILL_RADIAL_180 := 4
const FILL_RADIAL_360 := 5

const OBJECT_PROP_TEXT := 0
const OBJECT_PROP_ICON := 1
const OBJECT_PROP_COLOR := 2
const OBJECT_PROP_OUTLINE_COLOR := 3
const OBJECT_PROP_PLAYING := 4
const OBJECT_PROP_FRAME := 5
const OBJECT_PROP_DELTA_TIME := 6
const OBJECT_PROP_TIME_SCALE := 7
const OBJECT_PROP_FONT_SIZE := 8
const OBJECT_PROP_SELECTED := 9
