class_name FGUIEvents
extends RefCounted

const CLICK := "onClick"
const RIGHT_CLICK := "onRightClick"
const TOUCH_BEGIN := "onTouchBegin"
const TOUCH_MOVE := "onTouchMove"
const TOUCH_END := "onTouchEnd"
const ROLL_OVER := "onRollOver"
const ROLL_OUT := "onRollOut"
const MOUSE_WHEEL := "onMouseWheel"
const ADDED_TO_STAGE := "onAddedToStage"
const REMOVED_FROM_STAGE := "onRemovedFromStage"
const KEY_DOWN := "onKeyDown"
const CLICK_LINK := "onClickLink"
const FOCUS_IN := "onFocusIn"
const FOCUS_OUT := "onFocusOut"
const STATE_CHANGED := "onChanged"
const XY_CHANGED := "onPositionChanged"
const SIZE_CHANGED := "onSizeChanged"
const SIZE_DELAY_CHANGE := "fui_size_delay_change"
const CLICK_ITEM := "onClickItem"
const RIGHT_CLICK_ITEM := "onRightClickItem"
const SCROLL := "onScroll"
const SCROLL_END := "onScrollEnd"
const DROP := "onDrop"
const DRAG_START := "onDragStart"
const DRAG_MOVE := "onDragMove"
const DRAG_END := "onDragEnd"
const PULL_DOWN_RELEASE := "onPullDownRelease"
const PULL_UP_RELEASE := "onPullUpRelease"
const GEAR_STOP := "onGearStop"
const STAGE_RESIZED := "onStageResized"
const PLAY_END := "onPlayEnd"
const GRIP_TOUCH_END := "onGripTouchEnd"
const SUBMIT := "onSubmit"
const POPUP := "onPopup"
const CLOSE := "onClose"
